### ISSUE TITLE
Requesting Offline Token results in Error

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [SatelCreative/spylib#30]
When triggering the OAuth code callback, the following error is thrown:

`spylib.oauth.router:shopify_callback:78 - Could not retrieve offline token for shop <SHOPNAME>.myshopify.com`

This is a custom error, which is thrown from the following stack trace:

```
Traceback (most recent call last):
[2021-09-22T20:38:20.397Z]   File "venv/lib/python3.9/site-packages/anyio/streams/tls.py", line 102, in _call_sslobject_method
[2021-09-22T20:38:20.397Z]     result = func(*args)
[2021-09-22T20:38:20.397Z]              │     └ (65536,)
[2021-09-22T20:38:20.397Z]              └ <bound method SSLObject.read of <ssl.SSLObject object at 0x7f79c99844f0>>
[2021-09-22T20:38:20.397Z]   File ".pyenv/versions/3.9.6/lib/python3.9/ssl.py", line 888, in read
[2021-09-22T20:38:20.397Z]     v = self._sslobj.read(len)
[2021-09-22T20:38:20.397Z]         │    │       │    └ 65536
[2021-09-22T20:38:20.397Z]         │    │       └ <method 'read' of '_ssl._SSLSocket' objects>
[2021-09-22T20:38:20.397Z]         │    └ <_ssl._SSLSocket object at 0x7f79c9924930>
[2021-09-22T20:38:20.397Z]         └ <ssl.SSLObject object at 0x7f79c99844f0>
[2021-09-22T20:38:20.397Z] Executed 'Functions.webapp' (Succeeded, Id=0d9bcc79-1888-4375-b2de-0a57b0eb9db6, Duration=12ms)
[2021-09-22T20:38:20.397Z] ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2633)
```

**Comment by Nathan-Nesbitt** [comment]
This later leads to the following error 

```
RuntimeError: Task <Task pending name='Task-12' coro=<AsgiResponse.from_app() running at 
/usr/lib/azure-functions-core-tools-3/workers/python/3.9/LINUX/X64/azure/functions/_http_asgi.py:65> 
cb=[_run_until_complete_cb() at /home/nathan/.pyenv/versions/3.9.6/lib/python3.9/asyncio/base_events.py:184]> 
got Future <Future pending> attached to a different loop
```

**Comment by Nathan-Nesbitt** [comment]
This was caused by an infinite redirect problem on the front end, as long as the base URI is set properly this works. #31 covers the related issue that spawns from this.
